### ISSUE TITLE
random hello

### ISSUE THREAD

**Issue by andreineculau** [roehling/git-archive-all#1]
Thanks for creating and publishing this! A pleasure to see another Bats user 👏 

Could I kindly ask you to consider to

* use bash from the env e.g. `#!/usr/bin/env bash`
* link to this git repo in the header of the `git-archive-all` script, e.g. https://github.com/elasticdog/transcrypt/blob/main/transcrypt

**Comment by andreineculau** [comment]
another consideration: `getopt -l` for compatibility with gnu's getopt (which has a long version `--longoptions` instead of the bsd `--long`)

PS: pod2text. that was a new thing for me.

**Comment by andreineculau** [comment]
Just for clarity, closing this ticket means that you don't want to link to this repository? Since this script, just like transcrypt that i linked to, has higher chances to be copied in a codebase than to be imported (e.g. submodule) means that it's harder for someone to find the source, update it etc. Just making sure. Thanks for the other two commits!

**Comment by roehling** [comment]
Hi! Yes, I thought about it and decided and don't want to put any links in the code itself. But thank you for the other two suggestions, they were appreciated.
